### ISSUE TITLE
client crashes with KeyError if they try to move an entity

### ISSUE THREAD

**Issue by ThomasTetz** [ShallyBanh/RPGenerator#101]
```
unpickling
jsonunpickling
the async message is ['update_game', [8, 27]]
recieved something via select!
updating game
UPDATE GAME FLAG WAS SET, GETTING GAME
[client] [get_game_from_room_number] attempting to get a game blob from the 27
(474, 276)
(510, 305)
Move
(826, 432)
Traceback (most recent call last):
  File "play_game.py", line 1066, in <module>
    main_menu.mainloop(events)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 322, in account_login_view
    option_menu.mainloop(playevents)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 716, in join_game_view
    enter_room(room_number = room_number.get_text())
  File "play_game.py", line 910, in enter_room
    gameView.main(client, game, client_id, False)
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/game_view.py", line 1085, in main
    my_entity = game.ruleset_copy.move_entity(my_entity, (x,y))
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/game_engine/rule_enactor.py", line 57, in move_entity
    del self.all_created_entities[(entity.x, entity.y)]
KeyError: (5, 9)
```

**Comment by Mara2020** [comment]
fixed. has to do with the fact that keys are decoded by json as STRINGS rather than real tuples. fixed on back end with rule enactor
