### ISSUE TITLE
THOMAS

### ISSUE THREAD

**Issue by ShallyBanh** [ShallyBanh/RPGenerator#109]
sent async message
(587, 64)
(92, 140)
(389, 186)
(413, 429)
[client] [get_game_from_room_number] attempting to get a game blob from the 30
going to send async message ['join_game', ['30', 'shally']]
jsonpickling
pickling
trying to send pickle of size 74
sent async message
selected was: <socket.socket fd=25, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.31.51.108', 61389)>
equal to general connection
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "play_game.py", line 164, in async_receive
    saved = inm.recv(BUFFERSIZE)
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by Mara2020** [comment]
Hard to spot error. Waiting for the next time this occurs to more carefully dissect the issue.
