### ISSUE TITLE
Entities are gone when the GM leaves the game and then rejoins

### ISSUE THREAD

**Issue by Mara2020** [ShallyBanh/RPGenerator#110]

**Comment by ThomasTetz** [comment]
```
[client] [load_existing_rulesets] attempting to load rulesets from user with username t
[client] [get_game_id] attempting to load game history from user with username t
9
[client] [create_game] attempting to create a game with gameBlob, gameName, username = {"py/object": "game_engine.game.Game", "GM": {"py/object": "account.user.User", "_assets": {}, "_email": "t", "_password": null, "_username": "t"}, "assets": [], "map": {"py/object": "game_engine.map.Map", "fogOfWar": [[true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true], [true, true, true, true, true, true, true, true, true, true]], "height": 10, "textures": {}, "tilesize": 50, "width": 10}, "name": "t", "players": [], "ruleset_copy": null, "transcript": "", "uniqueID": 10},t,t
[client] [create_game] response was <Response [200]>/200/
going to send async message ['start_game', [10]]
jsonpickling
pickling
trying to send pickle of size 63
sent async message
gameObj ruleset_copy is None
[client] [get_assets] attempting to get_assets with username = t
response.status_code: 200 (<class 'int'>)
Traceback (most recent call last):
  File "play_game.py", line 1070, in <module>
    main_menu.mainloop(events)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 326, in account_login_view
    option_menu.mainloop(playevents)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 813, in create_new_game_view
    create_room(inputList[0], jsonpickle.decode(rulesetObject), inputList[2], inputList[3])
  File "play_game.py", line 942, in create_room
    gameView.main(client, game, client_id, True, ruleset_object)
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/game_view.py", line 981, in main
    game.ruleset_copy.parse_validator(validatorObj)
AttributeError: 'NoneType' object has no attribute 'parse_validator'
```
