### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by Mara2020** [ShallyBanh/RPGenerator#123]
[client] [update_game] attempting to update a game with gameId= 3
[client] [update_game] response was <Response [200]>/200/
going to send async message ['update_game', [2, 3]]
jsonpickling
pickling
trying to send pickle of size 66
Traceback (most recent call last):
  File "play_game.py", line 1083, in <module>
    main_menu.mainloop(events)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 337, in account_login_view
    option_menu.mainloop(playevents)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 731, in join_game_view
    enter_room(room_number = room_number.get_text())
  File "play_game.py", line 917, in enter_room
    gameView.main(client, game, client_id, True)
  File "/Users/biancaangotti/Documents/Year_5/ECE 493/RPGenerator/game_view.py", line 1107, in main
    GAMEVIEW.send_update_to_all()
  File "/Users/biancaangotti/Documents/Year_5/ECE 493/RPGenerator/game_view.py", line 51, in send_update_to_all
    async_send(["update_game", [client_id, game.get_uniqueID()]])
  File "/Users/biancaangotti/Documents/Year_5/ECE 493/RPGenerator/play_game.py", line 108, in async_send
    general_async_connection.sendall(pickled)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Mara2020** [comment]
Error that is hard to map because the pipe will disconnect at various times. Need to figure out a way to maintain a more consistent connection or find a way to properly disconnect the program when this error occurs rather than crash.
