### ISSUE TITLE
Deleting an entity no longer work because the dictionary needed to be manually updated

### ISSUE THREAD

**Issue by Mara2020** [ShallyBanh/RPGenerator#63]
```
Traceback (most recent call last):
  File "game_view.py", line 852, in <module>
    main()
  File "game_view.py", line 832, in main
    GM_HOTKEYS[event.unicode]["function"]()
  File "game_view.py", line 350, in delete_entity
    ruleenactor.remove_entity(saved_entity)
  File "/Users/biancaangotti/Documents/Year_5/ECE 493/RPGenerator/game_engine/rule_enactor.py", line 62, in remove_entity
    del self.all_created_entities[(x,y)]
KeyError: (4, 9)
```

**Comment by AndrewMcKernan** [comment]
Deleting and re-adding entities to the dictionary all_created_entities is now automatically done by the RuleEnactor. The commit referenced above fixes the issue on the GUI side (ddb8b742872f3acbf3a1ddb5f1dfeadf4c1637cf).
