### ISSUE TITLE
player rejoining a game they forcefully quit (ctrl-c etc) causes GM to crash

### ISSUE THREAD

**Issue by ThomasTetz** [ShallyBanh/RPGenerator#95]
```
selected was: <socket.socket fd=26, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.85', 53960), raddr=('204.209.76.191', 5000)>
equal to general connection
[b'\x80\x03X-\x00\x00\x00["join_request", [[6, "bangotti", null], 13]]', b'']
b'\x80\x03X-\x00\x00\x00["join_request", [[6, "bangotti", null], 13]]q\x00.'
unpickling
jsonunpickling
the async message is ['join_request', [[6, 'bangotti', None], 13]]
recieved something via select!
in the main trying to do the join loop
[[6, 'bangotti', None], 13]
IM IN THE JOIN REQUEST POPUP
going to send async message ['accept_join', [[6, 'bangotti', None], 13]]
jsonpickling
pickling
trying to send pickle of size 87
Traceback (most recent call last):
  File "play_game.py", line 1044, in <module>
    main_menu.mainloop(events)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 318, in account_login_view
    option_menu.mainloop(playevents)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 628, in mainloop
    if self._main():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 555, in _main
    self._select()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pygameMenu/menu.py", line 741, in _select
    option()
  File "play_game.py", line 712, in join_game_view
    enter_room(room_number = room_number.get_text())
  File "play_game.py", line 895, in enter_room
    gameView.main(client, game, client_id, True)
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/game_view.py", line 1017, in main
    GAMEVIEW.join_request_popup()
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/game_view.py", line 229, in join_request_popup
    async_send(['accept_join', shared_var.MESSAGE_CONTENT])
  File "/Users/thomas/Documents/University/10_Winter 2019/ece493/repo/play_game.py", line 100, in async_send
    general_async_connection.sendall(pickled)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Mara2020** [comment]
@ShallyBanh  fixed this error by creating a signal handler to control the actions taken when a player hits control-C on the keyboard, hence stopping the program. It sends a leave request to the server, thereby updating the room client numbers. This fixes the crash on the GM's side as the user was properly removed from the room.
